export default {
  LOGIN: '/',
  FOODS: '/comidas',
  DRINKS: '/bebidas',
  FOOD_DETAILS: '/comidas/:id',
  DRINK_DETAILS: '/bebidas/:id',
  FOOD_IN_PROGRESS: '/comidas/:id/in-progress',
  DRINK_IN_PROGRESS: '/bebidas/:id/in-progress',
  EXPLORE: '/explorar',
  EXPLORE_FOOD: '/explorar/comidas',
  EXPLORE_DRINK: '/explorar/bebidas',
  FOOD_BY_INGREDIENTS: '/explorar/comidas/ingredientes',
  DRINK_BY_INGREDIENTS: '/explorar/bebidas/ingredientes',
  FOOD_BY_AREA: '/explorar/comidas/area',
  PROFILE_PAGE: '/perfil',
  DONE_RECIPES: '/receitas-feitas',
  FAVORITE_RECIPES: '/receitas-favoritas',
};
