export default {
  GET_RECIPES: 'GET_RECIPES',
  REQUEST_RECIPES: 'REQUEST_RECIPES',
  SET_SEARCH_OPTIONS: 'SET_SEARCH_OPTIONS',
  CLEAR_RECIPES: 'CLEAR_RECIPES',
  REQUEST_CATEGORIES: 'REQUEST_CATEGORIES',
  GET_CATEGORIES: 'GET_CATEGORIES',
};
